name: generate-images

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Generate images
      run: rm -rf images && php quote_to_images.php

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update images dir
