name: generate-images

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Generate images
      run: |
        curl https://kumisystems.dl.sourceforge.net/project/linuxlibertine/linuxlibertine/5.3.0/LinLibertineTTF_5.3.0_2012_07_02.tgz && \
        tar xvf LinLibertineTTF_5.3.0_2012_07_02.tgz && \
        rm -rf images && \
        php quote_to_image.php

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update images dir
